version: 3.9;
## react/pacage.json 'proxy' must equal web-server ipv4_address if no access to localhost
services: 
  database:
    networks:            
         # you may set custom IP addresses            
         front:                
             ipv4_address: 192.168.0.4
    image: mongo:5.0-focal
    restart: always
    hostname: ledocker
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    ports: 
      - "${EXTERNAL_DB}:${INTERNAL_DB}"


  web-server:
    networks:            
         # you may set custom IP addresses            
         front:                
             ipv4_address: 192.168.0.40              
    build:
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNSTRING=mongodb://${DB_USER}:${DB_PASS}@ledocker:${INTERNAL_DB}
      - DBNAME=${DBNAME}
      - SESSION_SECRET=${SESSION_SECRET}
      - ITERATIONS=${ITERATIONS}
      - KEYLEN=${KEYLEN}
      - DIGEST=${DIGEST}
    depends_on:
      - database
    ports:
      - "${EXTERNAL_APP}:${INTERNAL_APP}"


  react-app:
    networks:            
         # you may set custom IP addresses            
         front:                
             ipv4_address: 192.168.0.41       
    build:
      dockerfile: ./react/dockerfilecompose
    environment:
      - MONGODB_CONNSTRING=mongodb://${DB_USER}:${DB_PASS}@ledocker:${INTERNAL_DB}
      - DBNAME=${DBNAME}
      - SESSION_SECRET=${SESSION_SECRET}
      - ITERATIONS=${ITERATIONS}
      - KEYLEN=${KEYLEN}
      - DIGEST=${DIGEST}
    depends_on:
      - database
    ports:
      - "${EXTERNAL_FE}:${INTERNAL_FE}"

networks:    
   front:        
       driver: bridge           
       ipam:            
          driver: default            
          config:                
              - subnet: 192.168.0.0/24                
                gateway: 192.168.0.3                 
